language: node_js
node_js:
  - "0.12"
  - "0.10"
notifications:
  email: false
branches:
  only:
    - master
    - develop

after_success: "<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js"
